name: Assembly/C CI
on:
  push:
  pull_request:
jobs:
  build:
    name: Build KernelOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install 32-bit GCC libraries
        run: sudo apt-get install gcc-multilib -y
      - name: Run build script
        run: ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/KernelOS.iso
